### PR TITLE
Add OCP4 Backup and Restore documentation

### PR DESCRIPTION
**Pull request by sbarre-esit**
Per https://app.zenhub.com/workspaces/openshift-4-build-out-5db73142897668000144f22b/issues/bcdevops/openshift4-rollout/317

### CODE REVIEW

**Review by jefkel — CHANGES_REQUESTED** [review]
Could you rename to OCP4-Storage-backup.md (less confusion when looking at this folder)?

I didn't see specific wording / note that this storageClass was only available on OCP4 - was this intentional?

**Comment by sbarre-esit** [comment]
OCP4 was in the tags and description, but that may not be enough so I've also added to the title.

**Review by jefkel — APPROVED** [review]
Looks good to me

**Review by patricksimonian — APPROVED** [review]

**Comment by patricksimonian** [comment]
:fire:

**Pull request merged**
