### PR TITLE
Service Description suggestions

### PR DESCRIPTION
**Pull request by StevenBarre**

### CODE REVIEW

**Comment by StevenBarre** [comment]
Suggestion: add a definitions section? Who is "we" ? Who are "product teams"?

**Comment by StevenBarre** [comment]
+1 for "fully funded" included in who should use Gold.

**Comment by StevenBarre** [comment]
Are the uptime numbers tied to the service agreement with AdvSol?

**Comment by StevenBarre** [comment]
Could we get a higher res / less blurry version of the Diagram? Also it should get uploaded to a images folder, instead of pulled off of the usercontent site.

**Comment by StevenBarre** [comment]
Do we want to include something about calling 77000 for after hours support if the cluster is down?

**Comment by StevenBarre** [comment]
@mitovskaol @juhewitt See this PR for some suggested changes to the Service Definition doc. Also check the PR for a bunch of questions I left in comments.

**Review by mitovskaol — APPROVED** [review]

**Comment by mitovskaol** [comment]
> Are the uptime numbers tied to the service agreement with AdvSol?

I believe so as they have been confirmed by David Ell.

**Pull request merged**
